[package]
name = "project-euler-rust"
version = "0.1.0"
authors = ["Robert Stratton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2"

[lib]
name = "primes"
path = "lib/primes.rs"